services:
  odoo:
    image: ${ODOO_IMAGE}:${ODOO_TAG}
    env_file:
      - ./.env
    environment:
      HOST: pg-main
      PORT: 5432
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${ODOO_PORT:-8069}:8069"
      - "${ODOO_LONGPOLL_PORT:-8072}:8072"
    volumes:
      - odoo_data:/var/lib/odoo
    restart: unless-stopped
    networks:
      - shared_backend

volumes:
  odoo_data:

networks:
  shared_backend:
    external: true
